
import java.awt.Color;
import java.sql.ResultSet;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sourabh
 */
public class eBookPdf extends javax.swing.JFrame {
String Username;
    /**
     * Creates new form eBookPdf
     * @param username
     */
    public eBookPdf(String username){
    this();
        this.Username=username;
         try{String sql =String.format("select Gid from groupjoin where type='%s'",Username);
    ResultSet rs=DBConnection.executeQuery(sql);
    rs.last();
    int l=rs.getRow();
    rs.beforeFirst();
    String arr[] =new String[l];
    int i=0;
    while(rs.next())
    {
        String val=rs.getString(1);
        arr[i++]=val;
        System.out.println(val);
  
    }
    listJoinedList.setListData(arr);
    
    }catch(Exception e){
        System.out.println(e);}
    }
    public eBookPdf() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setBackground(new Color(0,0,0,0));
        pnlDash.setBackground(new Color(0,0,0,111));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDash = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listJoinedList = new javax.swing.JList<>();
        btnSelsct = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listSelectedList = new javax.swing.JList<>();
        btnDownload = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlDash.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Birch Std", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ic_cloud_download_white_48dp_2x.png"))); // NOI18N
        jLabel1.setText("E-Books Download");
        pnlDash.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 340, 90));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listJoinedList.setBackground(new java.awt.Color(153, 153, 153));
        jScrollPane1.setViewportView(listJoinedList);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 270, 230));

        btnSelsct.setBackground(new java.awt.Color(153, 153, 153));
        btnSelsct.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSelsct.setForeground(new java.awt.Color(255, 255, 255));
        btnSelsct.setText("select");
        btnSelsct.setBorder(null);
        btnSelsct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelsctActionPerformed(evt);
            }
        });
        jPanel1.add(btnSelsct, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 90, 20));

        pnlDash.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 310, 300));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listSelectedList.setBackground(new java.awt.Color(153, 153, 153));
        listSelectedList.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(listSelectedList);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 20, 250, 230));

        btnDownload.setBackground(new java.awt.Color(153, 153, 153));
        btnDownload.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDownload.setForeground(new java.awt.Color(255, 255, 255));
        btnDownload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ic_file_download_black_24dp_1x.png"))); // NOI18N
        btnDownload.setText("Download");
        btnDownload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDownloadActionPerformed(evt);
            }
        });
        jPanel2.add(btnDownload, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, -1, 20));

        pnlDash.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, 300, 300));

        btnBack.setBackground(new java.awt.Color(153, 153, 153));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.setBorder(null);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        pnlDash.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, 90, 20));

        getContentPane().add(pnlDash, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
new studentDashboard().setVisible(true);
this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed
String s;
    private void btnSelsctActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelsctActionPerformed
        s = (String) listJoinedList.getSelectedValue();
         System.out.println(s);
          try{String sql =String.format("select ebookname from appgroup where Sid='%s'",s);
    ResultSet rs=DBConnection.executeQuery(sql);
    rs.last();
    int l=rs.getRow();
    rs.beforeFirst();
    String arr[] =new String[l];
    int i=0;
    while(rs.next())
    {
        String val=rs.getString(1);
        arr[i++]=val;
        System.out.println(val);
  
    }
    listSelectedList.setListData(arr);
    
    }catch(Exception e){
        System.out.println(e);}
    }//GEN-LAST:event_btnSelsctActionPerformed

    private void btnDownloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDownloadActionPerformed
        try{  
            String str = (String) listSelectedList.getSelectedValue();
         System.out.println(s);
         String sql=String.format("select URL from appgroup where Sid='%s' and ebookname='%s'",s,str);
       ResultSet rs= DBConnection.executeQuery(sql);
       rs.next();
       String url=rs.getString(1);
java.awt.Desktop.getDesktop().browse(java.net.URI.create(url));
        
        
        }catch(Exception e)
        {System.out.println(e);}
    }//GEN-LAST:event_btnDownloadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(eBookPdf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(eBookPdf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(eBookPdf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(eBookPdf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new eBookPdf().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDownload;
    private javax.swing.JButton btnSelsct;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> listJoinedList;
    private javax.swing.JList<String> listSelectedList;
    private javax.swing.JPanel pnlDash;
    // End of variables declaration//GEN-END:variables
}
