
import java.awt.Color;
import java.sql.ResultSet;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sourabh
 */
public class GroupDashboard extends javax.swing.JFrame {
 String username;
    /**
     * Creates new form GroupDashboard
     * @param name
     */
    public GroupDashboard(String name)
    {this();
        this.username=name;
    
    }
    public GroupDashboard() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setBackground(new Color(0,0,0,0));
        pnlDashView.setBackground(new Color(0,0,0,111));
        pnlTitle.setBackground(new Color(0,0,0,99));
        pnlSidePane.setBackground(new Color(0,0,0,116));
        pnlBack.setVisible(false);     
 pnlAddEBookWork.setVisible(false);
      pnlShowEBookWork.setVisible(false);
      lblTitle.setText(username);
      
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlSidePane = new javax.swing.JPanel();
        pnlAddEBook = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlShowEbook = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pnlDashView = new javax.swing.JPanel();
        pnlTitle = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        pnlBack = new javax.swing.JPanel();
        pnlShowEBookWork = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ListShowEbook = new javax.swing.JList<>();
        btnDelete = new javax.swing.JButton();
        pnlAddEBookWork = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtEBook = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        txtURL = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlSidePane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlAddEBook.setBackground(new java.awt.Color(102, 102, 102));
        pnlAddEBook.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ic_cloud_download_white_48dp_1x.png"))); // NOI18N
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        pnlAddEBook.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 60));

        pnlSidePane.add(pnlAddEBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 70, 60));

        pnlShowEbook.setBackground(new java.awt.Color(102, 102, 102));
        pnlShowEbook.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ic_line_weight_white_48dp_1x.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        pnlShowEbook.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 60, 50));

        pnlSidePane.add(pnlShowEbook, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 70, 70));

        getContentPane().add(pnlSidePane, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 0, 70, 540));

        pnlDashView.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlTitle.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Garamond", 1, 36)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Group Name");
        pnlTitle.add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 230, 80));

        pnlDashView.add(pnlTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 290, 110));

        pnlBack.setBackground(new java.awt.Color(51, 51, 51));
        pnlBack.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlShowEBookWork.setBackground(new java.awt.Color(153, 153, 153));
        pnlShowEBookWork.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ListShowEbook.setBackground(new java.awt.Color(102, 102, 102));
        ListShowEbook.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ListShowEbook.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(ListShowEbook);

        pnlShowEBookWork.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 404, 300));

        btnDelete.setBackground(new java.awt.Color(102, 102, 102));
        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        pnlShowEBookWork.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, 90, 20));

        pnlBack.add(pnlShowEBookWork, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 450, 360));

        pnlAddEBookWork.setBackground(new java.awt.Color(153, 153, 153));
        pnlAddEBookWork.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Book URL");
        pnlAddEBookWork.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 100, 20));

        txtEBook.setBackground(new java.awt.Color(153, 153, 153));
        txtEBook.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtEBook.setForeground(new java.awt.Color(255, 255, 255));
        txtEBook.setCaretColor(new java.awt.Color(255, 255, 255));
        pnlAddEBookWork.add(txtEBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, 270, 20));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        pnlAddEBookWork.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 62, 270, 10));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Book Name");
        pnlAddEBookWork.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 100, 20));

        txtURL.setBackground(new java.awt.Color(153, 153, 153));
        txtURL.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtURL.setForeground(new java.awt.Color(255, 255, 255));
        txtURL.setCaretColor(new java.awt.Color(255, 255, 255));
        txtURL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtURLActionPerformed(evt);
            }
        });
        pnlAddEBookWork.add(txtURL, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 270, 20));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        pnlAddEBookWork.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 270, 10));

        btnAdd.setBackground(new java.awt.Color(51, 51, 51));
        btnAdd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(255, 255, 255));
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        pnlAddEBookWork.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, 110, 23));

        btnEdit.setBackground(new java.awt.Color(51, 51, 51));
        btnEdit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        pnlAddEBookWork.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 110, 23));

        btnSave.setBackground(new java.awt.Color(51, 51, 51));
        btnSave.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        pnlAddEBookWork.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 110, 23));

        pnlBack.add(pnlAddEBookWork, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, 540, 220));

        pnlDashView.add(pnlBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 120, 700, 390));

        btnLogout.setBackground(new java.awt.Color(153, 153, 153));
        btnLogout.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setText("LogOut");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        pnlDashView.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 10, -1, -1));

        getContentPane().add(pnlDashView, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
      pnlBack.setVisible(true);
      pnlAddEBookWork.setVisible(true);
      pnlShowEBookWork.setVisible(false);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
pnlBack.setVisible(true);     
 pnlAddEBookWork.setVisible(false);
      pnlShowEBookWork.setVisible(true);
      try{String sql =String.format("select ebookname from appgroup where Sid='%s'",username);
    ResultSet rs=DBConnection.executeQuery(sql);
    rs.last();
    int l=rs.getRow();
    rs.beforeFirst();
    String arr[] =new String[l];
    int i=0;
    while(rs.next())
    {
        String val=rs.getString(1);
        arr[i++]=val;
        System.out.println(val);
  
    }
    ListShowEbook.setListData(arr);
    
    }catch(Exception e){
        System.out.println(e);}
    }//GEN-LAST:event_jLabel2MouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void txtURLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtURLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtURLActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
       String bookName,url;
       bookName=txtEBook.getText();
       url=txtURL.getText();
       try{String sql=String.format("insert into appgroup values('%s','%s','%s')",username,bookName,url);
       DBConnection.executeUpdate(sql);
       DBConnection.commit();
       }catch(Exception e){}
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
       String bookName;btnAdd.setVisible(false);btnEdit.setVisible(false);
       bookName=txtEBook.getText().trim();
       try{String sql=String.format("select URL from appgroup where Sid='%s' and bookname='%s'",username,bookName);
       ResultSet rs=DBConnection.executeQuery(sql);
       rs.next();
       String url=rs.getString(1);
       txtURL.setText(url);
       }catch(Exception e){System.out.println(e);}
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
         String bookName,url;
       bookName=txtEBook.getText().trim();
       url=txtURL.getText().trim();
       try{String sql=String.format("update appgroup set bookname='%s',URL='%s'where Sid='%s'",bookName,url,username);
       DBConnection.executeUpdate(sql);
       DBConnection.commit();
       }catch(Exception e){}
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
  try {
            String sql = String.format("update appuser set status=1 where Sid='%s'", username);
            DBConnection.executeUpdate(sql);
            DBConnection.commit();
        } catch (Exception e) {
            System.out.println(e);
        }
        new loginFrameUI().setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GroupDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GroupDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GroupDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GroupDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GroupDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> ListShowEbook;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlAddEBook;
    private javax.swing.JPanel pnlAddEBookWork;
    private javax.swing.JPanel pnlBack;
    private javax.swing.JPanel pnlDashView;
    private javax.swing.JPanel pnlShowEBookWork;
    private javax.swing.JPanel pnlShowEbook;
    private javax.swing.JPanel pnlSidePane;
    private javax.swing.JPanel pnlTitle;
    private javax.swing.JTextField txtEBook;
    private javax.swing.JTextField txtURL;
    // End of variables declaration//GEN-END:variables
}
