
import java.awt.Color;
import java.sql.ResultSet;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sourabh
 */
public class joinGroup extends javax.swing.JFrame {
String Username;
    /**
     * Creates new form joinGroup
     * @param username
     */
        public joinGroup(String username)
    {this(); String ss="Group";
    try{String sql =String.format("select Sid from appuser where type='%s'",ss);
    ResultSet rs=DBConnection.executeQuery(sql);
    rs.last();
    int l=rs.getRow();
    rs.beforeFirst();
    String arr[] =new String[l];
    int i=0;
    while(rs.next())
    {
        String val=rs.getString(1);
        arr[i++]=val;
        System.out.println(val);
  
    }
    listGblList.setListData(arr);
    
    }catch(Exception e){
        System.out.println(e);}
        
    }
    public joinGroup() {
        initComponents();
//this.Username=username;
       
        this.setLocationRelativeTo(null);
        this.setBackground(new Color(0,0,0,0));
        pnlDashView.setBackground(new Color(0,0,0,111));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDashView = new javax.swing.JPanel();
        pnlGblGroup = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listGblList = new javax.swing.JList<>();
        btnJoin = new javax.swing.JButton();
        pnlJoinedGroup = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listJoinedList = new javax.swing.JList<>();
        lblReload = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlDashView.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlGblGroup.setBackground(new java.awt.Color(51, 51, 51));
        pnlGblGroup.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listGblList.setBackground(new java.awt.Color(153, 153, 153));
        listGblList.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        listGblList.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(listGblList);

        pnlGblGroup.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 290, 240));

        btnJoin.setBackground(new java.awt.Color(153, 153, 153));
        btnJoin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnJoin.setForeground(new java.awt.Color(255, 255, 255));
        btnJoin.setText("Join");
        btnJoin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJoinActionPerformed(evt);
            }
        });
        pnlGblGroup.add(btnJoin, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 290, 90, 20));

        pnlDashView.add(pnlGblGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 310, 340));

        pnlJoinedGroup.setBackground(new java.awt.Color(51, 51, 51));
        pnlJoinedGroup.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        listJoinedList.setBackground(new java.awt.Color(153, 153, 153));
        listJoinedList.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        listJoinedList.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setViewportView(listJoinedList);

        pnlJoinedGroup.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 290, 290));

        lblReload.setBackground(new java.awt.Color(51, 51, 51));
        lblReload.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ic_autorenew_white_36dp_1x.png"))); // NOI18N
        lblReload.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblReloadMouseClicked(evt);
            }
        });
        pnlJoinedGroup.add(lblReload, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 4, -1, -1));

        pnlDashView.add(pnlJoinedGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 110, 310, 340));

        jLabel1.setFont(new java.awt.Font("Birch Std", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ic_group_white_48dp_2x.png"))); // NOI18N
        jLabel1.setText("        Group");
        pnlDashView.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 270, 90));

        btnBack.setBackground(new java.awt.Color(153, 153, 153));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBack.setForeground(new java.awt.Color(255, 255, 255));
        btnBack.setText("Back");
        btnBack.setBorder(null);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        pnlDashView.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 30, 80, 20));

        getContentPane().add(pnlDashView, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        new studentDashboard().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnJoinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJoinActionPerformed
         String s = (String) listGblList.getSelectedValue();
         System.out.println(s);
         try{
             String sql=String.format("insert into groupjoin values('%s','%s')",Username,s);
             DBConnection.executeUpdate(sql);
             DBConnection.commit();
            // DBConnection.close();
             
         }catch(Exception e){}
          
         
    }//GEN-LAST:event_btnJoinActionPerformed

    private void lblReloadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReloadMouseClicked
        
        try{String sql =String.format("select Gid from groupjoin where Sid='%s'",Username);
    ResultSet rs=DBConnection.executeQuery(sql);
    rs.last();
    int l=rs.getRow();
    rs.beforeFirst();
    String arr[] =new String[l];
    int i=0;
    while(rs.next())
    {
        String val=rs.getString(1);
        arr[i++]=val;
        System.out.println(val);
  
    }
    listJoinedList.setListData(arr);
    //DBConnection.close();
    }catch(Exception e){
        System.out.println(e);}
        
    }//GEN-LAST:event_lblReloadMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(joinGroup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(joinGroup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(joinGroup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(joinGroup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new joinGroup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnJoin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblReload;
    private javax.swing.JList<String> listGblList;
    private javax.swing.JList<String> listJoinedList;
    private javax.swing.JPanel pnlDashView;
    private javax.swing.JPanel pnlGblGroup;
    private javax.swing.JPanel pnlJoinedGroup;
    // End of variables declaration//GEN-END:variables
}
