
import java.awt.Color;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import oracle.net.aso.n;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sourabh
 */
public class loginFrameUI extends javax.swing.JFrame {

    /**
     * Creates new form loginFrameUI
     */
    public loginFrameUI() {
        initComponents();
        this.setLocationRelativeTo(null);
        pnlChoice.setBackground(new Color(0,0,0,99));
        pnlLogin.setBackground(new Color(0,0,0,99));
        this.setBackground(new Color(0,0,0,99));
        jPanel1.setBackground(new Color(0,0,0,0));
        
        txtId.setBackground(new Color(0,0,0,0));
        txtName.setBackground(new Color(0,0,0,0));
        txtBranch.setBackground(new Color(0,0,0,0));
        txtEmail.setBackground(new Color(0,0,0,0));
        txtMobile.setBackground(new Color(0,0,0,0));
        txtAddress.setBackground(new Color(0,0,0,0));
        txtPassword.setBackground(new Color(0,0,0,0));
         txtGroupName.setBackground(new Color(0,0,0,0));
        txtGroupEmail.setBackground(new Color(0,0,0,0));
        txtGroupMobile.setBackground(new Color(0,0,0,0));
        txtGroupPassword.setBackground(new Color(0,0,0,0));
         pnlLoginPane.setVisible(false);
         pnlGroup.setVisible(false);
     //    jPanel2.setBackground(new Color(0,0,0,0));
        System.out.println(pnlLoginPane.getBounds()+" ");
        pnlUserLogin.setVisible(true);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        pnlChoice = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        rdBtnTeacher = new javax.swing.JRadioButton();
        rdBtnStudent = new javax.swing.JRadioButton();
        rdBtnGroup = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        pnlLogin = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        pnlUserLogin = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        txtUserId = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        txtLoginPassword = new javax.swing.JPasswordField();
        jSeparator13 = new javax.swing.JSeparator();
        btnSignin = new javax.swing.JButton();
        txtForgetPassword = new javax.swing.JButton();
        pnlLoginPane = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtMobile = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtBranch = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        btnCreate = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        txtPassword = new javax.swing.JPasswordField();
        pnlGroup = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtGroupName = new javax.swing.JTextField();
        txtGroupEmail = new javax.swing.JTextField();
        txtGroupMobile = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        txtGroupPassword = new javax.swing.JPasswordField();
        jSeparator9 = new javax.swing.JSeparator();

        jTextField2.setText("jTextField2");

        jTextField3.setText("jTextField3");

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlChoice.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup2.add(rdBtnTeacher);
        rdBtnTeacher.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        rdBtnTeacher.setForeground(new java.awt.Color(255, 255, 255));
        rdBtnTeacher.setText("Library");
        rdBtnTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdBtnTeacherActionPerformed(evt);
            }
        });
        jPanel1.add(rdBtnTeacher, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        buttonGroup2.add(rdBtnStudent);
        rdBtnStudent.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        rdBtnStudent.setForeground(new java.awt.Color(255, 255, 255));
        rdBtnStudent.setText("User");
        rdBtnStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdBtnStudentActionPerformed(evt);
            }
        });
        jPanel1.add(rdBtnStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        buttonGroup2.add(rdBtnGroup);
        rdBtnGroup.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        rdBtnGroup.setForeground(new java.awt.Color(255, 255, 255));
        rdBtnGroup.setText("Group");
        rdBtnGroup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdBtnGroupActionPerformed(evt);
            }
        });
        jPanel1.add(rdBtnGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        pnlChoice.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, 150, 140));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("New User");
        pnlChoice.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, -1, -1));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Existing User? SignIn");
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });
        pnlChoice.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 350, -1, 20));

        getContentPane().add(pnlChoice, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 260, 680));

        pnlLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlUserLogin.setBackground(new java.awt.Color(102, 102, 102));
        pnlUserLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Password");
        pnlUserLogin.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        txtUserId.setBackground(new java.awt.Color(102, 102, 102));
        txtUserId.setForeground(new java.awt.Color(255, 255, 255));
        txtUserId.setToolTipText("for students Student Id ,for teachers Teacher Id , for group Group Name");
        txtUserId.setBorder(null);
        txtUserId.setCaretColor(new java.awt.Color(255, 255, 255));
        pnlUserLogin.add(txtUserId, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 220, 20));
        pnlUserLogin.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 220, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("User Id");
        pnlUserLogin.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        txtLoginPassword.setBackground(new java.awt.Color(102, 102, 102));
        txtLoginPassword.setForeground(new java.awt.Color(255, 255, 255));
        txtLoginPassword.setBorder(null);
        pnlUserLogin.add(txtLoginPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 220, 20));
        pnlUserLogin.add(jSeparator13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 162, 220, 10));

        btnSignin.setBackground(new java.awt.Color(51, 51, 51));
        btnSignin.setForeground(new java.awt.Color(255, 255, 255));
        btnSignin.setText("Sign In");
        btnSignin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSigninActionPerformed(evt);
            }
        });
        pnlUserLogin.add(btnSignin, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 80, 20));

        txtForgetPassword.setBackground(new java.awt.Color(51, 51, 51));
        txtForgetPassword.setForeground(new java.awt.Color(255, 255, 255));
        txtForgetPassword.setText("Forget Password");
        txtForgetPassword.setBorder(null);
        txtForgetPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtForgetPasswordActionPerformed(evt);
            }
        });
        pnlUserLogin.add(txtForgetPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 110, 20));

        jPanel2.add(pnlUserLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 180, 280, 230));

        pnlLoginPane.setBackground(new java.awt.Color(102, 102, 102));
        pnlLoginPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Password");
        pnlLoginPane.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, 80, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Name");
        pnlLoginPane.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 40, -1));

        jLabel4.setBackground(new java.awt.Color(102, 102, 102));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Designation");
        pnlLoginPane.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 120, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Mobile No");
        pnlLoginPane.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 70, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Library Id");
        pnlLoginPane.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 80, 20));

        txtMobile.setBackground(new java.awt.Color(102, 102, 102));
        txtMobile.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtMobile.setForeground(new java.awt.Color(255, 255, 255));
        txtMobile.setBorder(null);
        txtMobile.setCaretColor(new java.awt.Color(255, 255, 255));
        pnlLoginPane.add(txtMobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 280, 20));

        txtId.setBackground(new java.awt.Color(102, 102, 102));
        txtId.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtId.setForeground(new java.awt.Color(255, 255, 255));
        txtId.setBorder(null);
        txtId.setCaretColor(new java.awt.Color(255, 255, 255));
        txtId.setName("wwd"); // NOI18N
        pnlLoginPane.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 200, 20));
        txtId.getAccessibleContext().setAccessibleName("");

        txtName.setBackground(new java.awt.Color(102, 102, 102));
        txtName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtName.setForeground(new java.awt.Color(255, 255, 255));
        txtName.setBorder(null);
        txtName.setCaretColor(new java.awt.Color(255, 255, 255));
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        pnlLoginPane.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 145, 280, 20));

        txtBranch.setBackground(new java.awt.Color(102, 102, 102));
        txtBranch.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtBranch.setForeground(new java.awt.Color(255, 255, 255));
        txtBranch.setBorder(null);
        txtBranch.setCaretColor(new java.awt.Color(255, 255, 255));
        pnlLoginPane.add(txtBranch, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 215, 280, 20));

        txtEmail.setBackground(new java.awt.Color(102, 102, 102));
        txtEmail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(255, 255, 255));
        txtEmail.setBorder(null);
        txtEmail.setCaretColor(new java.awt.Color(255, 255, 255));
        pnlLoginPane.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 285, 280, 20));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        pnlLoginPane.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 200, -1));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        pnlLoginPane.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 280, 10));

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        pnlLoginPane.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 280, 10));

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        pnlLoginPane.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 280, -1));

        btnCreate.setBackground(new java.awt.Color(102, 102, 102));
        btnCreate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCreate.setForeground(new java.awt.Color(255, 255, 255));
        btnCreate.setText("Create Account");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        pnlLoginPane.add(btnCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 560, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Email Id");
        pnlLoginPane.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 70, 20));

        jSeparator11.setForeground(new java.awt.Color(255, 255, 255));
        pnlLoginPane.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 382, 280, 10));

        jSeparator12.setForeground(new java.awt.Color(255, 255, 255));
        pnlLoginPane.add(jSeparator12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 455, 280, 10));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Address");
        pnlLoginPane.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 80, 20));

        txtAddress.setBackground(new java.awt.Color(102, 102, 102));
        txtAddress.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtAddress.setForeground(new java.awt.Color(255, 255, 255));
        txtAddress.setBorder(null);
        txtAddress.setCaretColor(new java.awt.Color(255, 255, 255));
        pnlLoginPane.add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 280, 20));

        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));
        pnlLoginPane.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 535, 280, 10));

        txtPassword.setBackground(new java.awt.Color(102, 102, 102));
        txtPassword.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(255, 255, 255));
        txtPassword.setBorder(null);
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        pnlLoginPane.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 510, 280, 20));

        jPanel2.add(pnlLoginPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 15, 450, 610));

        pnlGroup.setBackground(new java.awt.Color(102, 102, 102));
        pnlGroup.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Group Name");
        pnlGroup.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 110, 20));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Email Id");
        pnlGroup.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 60, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Password");
        pnlGroup.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, 20));

        txtGroupName.setBackground(new java.awt.Color(102, 102, 102));
        txtGroupName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtGroupName.setForeground(new java.awt.Color(255, 255, 255));
        txtGroupName.setBorder(null);
        txtGroupName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGroupNameActionPerformed(evt);
            }
        });
        pnlGroup.add(txtGroupName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 270, 20));

        txtGroupEmail.setBackground(new java.awt.Color(102, 102, 102));
        txtGroupEmail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtGroupEmail.setForeground(new java.awt.Color(255, 255, 255));
        txtGroupEmail.setBorder(null);
        txtGroupEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGroupEmailActionPerformed(evt);
            }
        });
        pnlGroup.add(txtGroupEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 270, 20));

        txtGroupMobile.setBackground(new java.awt.Color(102, 102, 102));
        txtGroupMobile.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtGroupMobile.setForeground(new java.awt.Color(255, 255, 255));
        txtGroupMobile.setBorder(null);
        txtGroupMobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGroupMobileActionPerformed(evt);
            }
        });
        pnlGroup.add(txtGroupMobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 270, 20));

        jButton3.setBackground(new java.awt.Color(102, 102, 102));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Create Account");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        pnlGroup.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 360, 140, 20));

        jSeparator6.setForeground(new java.awt.Color(255, 255, 255));
        pnlGroup.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 95, 270, 10));

        jSeparator7.setForeground(new java.awt.Color(255, 255, 255));
        pnlGroup.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 175, 270, 10));

        jSeparator8.setForeground(new java.awt.Color(255, 255, 255));
        pnlGroup.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 265, 270, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Mobile No");
        pnlGroup.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, 20));

        txtGroupPassword.setBackground(new java.awt.Color(102, 102, 102));
        txtGroupPassword.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtGroupPassword.setForeground(new java.awt.Color(255, 255, 255));
        txtGroupPassword.setBorder(null);
        pnlGroup.add(txtGroupPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 270, 20));
        pnlGroup.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 345, 270, -1));

        jPanel2.add(pnlGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(65, 80, 400, 400));

        pnlLogin.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 530, 640));

        getContentPane().add(pnlLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 570, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rdBtnTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdBtnTeacherActionPerformed
      
         pnlLoginPane.setVisible(true);
         jLabel6.setText("Library Id");
         jLabel4.setText("Designation");
          pnlGroup.setVisible(false);
          pnlUserLogin.setVisible(false);
        
    }//GEN-LAST:event_rdBtnTeacherActionPerformed

    private void rdBtnStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdBtnStudentActionPerformed
         pnlLoginPane.setVisible(true);
         jLabel6.setText("User Id");
         jLabel4.setText("Branch");
         pnlGroup.setVisible(false);
         pnlUserLogin.setVisible(false);
          
    }//GEN-LAST:event_rdBtnStudentActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void txtGroupMobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGroupMobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGroupMobileActionPerformed

    private void txtGroupEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGroupEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGroupEmailActionPerformed

    private void rdBtnGroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdBtnGroupActionPerformed
        pnlGroup.setVisible(true);
        pnlLoginPane.setVisible(false);
        pnlUserLogin.setVisible(false);
    }//GEN-LAST:event_rdBtnGroupActionPerformed

    private void txtGroupNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGroupNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGroupNameActionPerformed

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        pnlGroup.setVisible(false);
        pnlLoginPane.setVisible(false);
         pnlUserLogin.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel14MouseClicked

    private void btnSigninActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSigninActionPerformed
String name,pwd,sql;
        name=txtUserId.getText().trim();
        pwd=String.valueOf(txtLoginPassword.getPassword()).trim();
      try{
      sql=String.format("select type,status from appuser where Sid ='%s' and password='%s'", name ,pwd);
          System.out.println(sql);
      ResultSet rs=DBConnection.executeQuery(sql);
      if(rs.next())
      {
          int status=rs.getInt("status");
          String type=rs.getString("type");
          String so=type.trim();
          System.out.println("status="+status+"type="+type);
          if(status==1)
          {
              
              sql=String.format("update appuser set status=0 where Sid='%s'", name);
              System.out.println(sql);
             DBConnection.executeUpdate(sql);
             DBConnection.commit();
             // System.out.println(n);
              System.out.println("something");
              /* if(n==0)
              {
              System.out.println("hey");
              JOptionPane.showMessageDialog(null,"status");
              return;
              }System.out.println(status);
              System.out.println("wo");*/
                //String Student="Student";
                //String Teacher="Teacher";
                System.out.println("0"+type+"1");
                String Group="Group";
                 if(so.equals("Student")) { System.out.println("type"+type);
                      new studentDashboard(name).setVisible(true);
                      this.dispose();
                     }
                 else if(so.equals("Teacher"))
                  {new teacherDashboard(name).setVisible(true);
                      this.dispose();
                      }
                 else if(so.equals(Group))
                  { new GroupDashboard(name).setVisible(true);
                      this.dispose();
                      }
                  
          }}}
      
      catch(Exception e)
      {
          System.out.println("hey"+e.getMessage());
      }
    }//GEN-LAST:event_btnSigninActionPerformed

    private void txtForgetPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtForgetPasswordActionPerformed
new ForgetPassword().setVisible(true);
this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_txtForgetPasswordActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        String Eid,Name,designation,email,password,branch,sql,mobile,type;
int status=1;
ResultSet rs;
if(rdBtnTeacher.isSelected()||rdBtnStudent.isSelected())
{Eid= txtId.getText().trim();
Name=txtName.getText().trim();
designation=txtBranch.getText().trim();
email=txtEmail.getText().trim();
mobile=txtMobile.getText().trim();
password=String.valueOf(txtPassword.getPassword()).trim();
if(rdBtnTeacher.isSelected()){type="Teacher";}
else{type="Student";}

try{
           sql=String.format("Insert into appuser values('%s','%s','%s','%s','%s','%s','%s','%d')",Eid,Name,designation,email,mobile,password,type,status);
           System.out.println(sql);
           DBConnection.executeUpdate(sql);
      DBConnection.commit();
       }catch(Exception e)
       {System.out.println(e+"hun");
           JOptionPane.showMessageDialog(null,"Account cannot be created");}
}
/*else if(rdBtnStudent.isSelected())
{Eid= txtId.getText();
Name=txtName.getText();
designation=txtBranch.getText();
email=txtEmail.getText();
mobile=txtMobile.getText();
password=String.valueOf(txtPassword.getPassword());
type="Student";
status=1;
}*/


  
    }//GEN-LAST:event_btnCreateActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
String Eid,email,mobile,password,type,sql;
String Name="",designation="";
int status=1;
        Eid= txtGroupName.getText();
email=txtGroupEmail.getText();
mobile=txtGroupMobile.getText();
password=String.valueOf(txtGroupPassword.getPassword());
type="Group";

    
try{
           sql=String.format("Insert into appuser values('%s','%s','%s','%s','%s','%s','%s','%d')",Eid,Name,designation,email,mobile,password,type,status);
           System.out.println(sql);
           DBConnection.executeUpdate(sql);
      DBConnection.commit();
       }catch(Exception e)
       {System.out.println(e+"hun");
           JOptionPane.showMessageDialog(null,"Account cannot be created");}        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginFrameUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginFrameUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginFrameUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginFrameUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginFrameUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCreate;
    private javax.swing.JButton btnSignin;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JPanel pnlChoice;
    private javax.swing.JPanel pnlGroup;
    private javax.swing.JPanel pnlLogin;
    private javax.swing.JPanel pnlLoginPane;
    private javax.swing.JPanel pnlUserLogin;
    private javax.swing.JRadioButton rdBtnGroup;
    private javax.swing.JRadioButton rdBtnStudent;
    private javax.swing.JRadioButton rdBtnTeacher;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtBranch;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JButton txtForgetPassword;
    private javax.swing.JTextField txtGroupEmail;
    private javax.swing.JTextField txtGroupMobile;
    private javax.swing.JTextField txtGroupName;
    private javax.swing.JPasswordField txtGroupPassword;
    private javax.swing.JTextField txtId;
    private javax.swing.JPasswordField txtLoginPassword;
    private javax.swing.JTextField txtMobile;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUserId;
    // End of variables declaration//GEN-END:variables
}
