
import java.awt.Color;
import java.sql.ResultSet;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sourabh
 */
public class studentDashboard extends javax.swing.JFrame {
String username;
    /**
     * Creates new form studentDashboard
     * @param name
     */
    public studentDashboard(String name){
        this.username=name;
        try{
            String sql=String.format("select*from appuser where Sid='%s'",username);
            ResultSet rs=DBConnection.executeQuery(sql);
            if(rs.next())
            {lblEnrollment.setText(rs.getString("Sid"));
            txtName.setText(rs.getString("name"));
            txtBranch.setText(rs.getString("Designation"));
            txtEmailId.setText(rs.getString("emailid"));
            }
            
        }catch(Exception e){System.out.println(""+e);}
    }
    public studentDashboard() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setBackground(new Color(0,0,0,100));
        pnlTask.setBackground(new Color(0,0,0,111));
        pnlDashView.setBackground(new Color(0,0,0,0));
        pnlDash.setBackground(new Color(0,0,0,0));
        pnlShortcutDash.setBackground(new Color(0,0,0,111));
        pnlShortcutDash.setVisible(false);
        pnlWork.setVisible(false);
        pnlIssuedBookWork.setVisible(false);
        btnSave.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlTask = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblEnrollment = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        txtAddress = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        txtBranch = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        txtEmailId = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        txtMobile = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        btnEdit = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        pnlDashView = new javax.swing.JPanel();
        pnlWork = new javax.swing.JPanel();
        pnlIssuedBookWork = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pnlDash = new javax.swing.JPanel();
        pnlJoinGroup = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pnlIssuedBook = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        pnlEbookDownload = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        pnlNotes = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        pnlShortcutDash = new javax.swing.JPanel();
        pnlShortcutNotes = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        pnlShortcutIssuedBook = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        pnlShortcutEbookdownload = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        pnlShortcutJoinGroup = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        pnlTask.setBackground(new java.awt.Color(51, 51, 51));
        pnlTask.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ic_account_circle_white_48dp_2x.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        pnlTask.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 90, 100));

        jLabel5.setBackground(new java.awt.Color(51, 51, 51));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Address");
        pnlTask.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 50, -1));

        lblEnrollment.setBackground(new java.awt.Color(51, 51, 51));
        lblEnrollment.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblEnrollment.setForeground(new java.awt.Color(255, 255, 255));
        pnlTask.add(lblEnrollment, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 90, 20));

        jLabel6.setBackground(new java.awt.Color(51, 51, 51));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Enrollment No");
        pnlTask.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 90, -1));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        pnlTask.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 200, -1));

        txtAddress.setEditable(false);
        txtAddress.setBackground(new java.awt.Color(51, 51, 51));
        txtAddress.setForeground(new java.awt.Color(255, 255, 255));
        txtAddress.setBorder(null);
        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });
        pnlTask.add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 480, 200, 20));

        jLabel7.setBackground(new java.awt.Color(51, 51, 51));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Name");
        pnlTask.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 40, -1));

        txtName.setEditable(false);
        txtName.setBackground(new java.awt.Color(51, 51, 51));
        txtName.setForeground(new java.awt.Color(255, 255, 255));
        txtName.setBorder(null);
        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        pnlTask.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 200, 20));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));
        pnlTask.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 292, 200, 10));

        jLabel8.setBackground(new java.awt.Color(51, 51, 51));
        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Branch");
        pnlTask.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 50, -1));

        txtBranch.setEditable(false);
        txtBranch.setBackground(new java.awt.Color(51, 51, 51));
        txtBranch.setForeground(new java.awt.Color(255, 255, 255));
        txtBranch.setBorder(null);
        txtBranch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBranchActionPerformed(evt);
            }
        });
        pnlTask.add(txtBranch, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 200, 20));

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));
        pnlTask.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 200, -1));

        jLabel9.setBackground(new java.awt.Color(51, 51, 51));
        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("EmailId");
        pnlTask.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 50, -1));

        txtEmailId.setEditable(false);
        txtEmailId.setBackground(new java.awt.Color(51, 51, 51));
        txtEmailId.setForeground(new java.awt.Color(255, 255, 255));
        txtEmailId.setBorder(null);
        txtEmailId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailIdActionPerformed(evt);
            }
        });
        pnlTask.add(txtEmailId, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 200, 20));

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));
        pnlTask.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 200, -1));

        jLabel10.setBackground(new java.awt.Color(51, 51, 51));
        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Mobile No");
        pnlTask.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 390, 60, -1));

        txtMobile.setEditable(false);
        txtMobile.setBackground(new java.awt.Color(51, 51, 51));
        txtMobile.setForeground(new java.awt.Color(255, 255, 255));
        txtMobile.setBorder(null);
        txtMobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMobileActionPerformed(evt);
            }
        });
        pnlTask.add(txtMobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 200, 20));

        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));
        pnlTask.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 500, 200, 10));

        btnEdit.setBackground(new java.awt.Color(102, 102, 102));
        btnEdit.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("Edit");
        btnEdit.setBorder(null);
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        pnlTask.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 530, 50, 20));

        btnLogout.setBackground(new java.awt.Color(102, 102, 102));
        btnLogout.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLogout.setForeground(new java.awt.Color(255, 255, 255));
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ic_exit_to_app_white_24dp_1x.png"))); // NOI18N
        btnLogout.setText("Logout");
        btnLogout.setBorder(null);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        pnlTask.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 110, -1));

        btnSave.setBackground(new java.awt.Color(153, 153, 153));
        btnSave.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        pnlTask.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 530, 50, 20));

        pnlDashView.setBackground(new java.awt.Color(153, 153, 153));
        pnlDashView.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlWork.setBackground(new java.awt.Color(51, 51, 51));
        pnlWork.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlIssuedBookWork.setBackground(new java.awt.Color(153, 153, 153));
        pnlIssuedBookWork.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setBackground(new java.awt.Color(153, 153, 153));
        jTable1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Book Id", "Book Name", "Book Author", "Issue Date", "Return Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        pnlIssuedBookWork.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, 100));

        pnlWork.add(pnlIssuedBookWork, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 450, 100));

        pnlDashView.add(pnlWork, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 620, 310));

        pnlDash.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlJoinGroup.setBackground(new java.awt.Color(102, 102, 102));
        pnlJoinGroup.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlJoinGroupMouseClicked(evt);
            }
        });
        pnlJoinGroup.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ic_group_add_black_48dp_1x.png"))); // NOI18N
        pnlJoinGroup.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Join Group");
        pnlJoinGroup.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 110, 30));

        pnlDash.add(pnlJoinGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 120, 220, 70));

        pnlIssuedBook.setBackground(new java.awt.Color(102, 102, 102));
        pnlIssuedBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlIssuedBookMouseClicked(evt);
            }
        });
        pnlIssuedBook.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ic_collections_bookmark_black_48dp_1x.png"))); // NOI18N
        pnlIssuedBook.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 40));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Issued books");
        pnlIssuedBook.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        pnlDash.add(pnlIssuedBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 23, 220, 70));

        pnlEbookDownload.setBackground(new java.awt.Color(102, 102, 102));
        pnlEbookDownload.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlEbookDownloadMouseClicked(evt);
            }
        });
        pnlEbookDownload.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ic_cloud_download_black_48dp_1x.png"))); // NOI18N
        pnlEbookDownload.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setText("Ebooks Download");
        pnlEbookDownload.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, -1, -1));

        pnlDash.add(pnlEbookDownload, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 230, 70));

        pnlNotes.setBackground(new java.awt.Color(102, 102, 102));
        pnlNotes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ic_assignment_black_48dp_1x.png"))); // NOI18N
        pnlNotes.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setText("Notes");
        pnlNotes.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 60, 30));

        pnlDash.add(pnlNotes, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 230, 70));

        pnlDashView.add(pnlDash, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 540, 220));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Dash Board");
        pnlDashView.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 330, 60));

        pnlShortcutDash.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlShortcutNotes.setBackground(new java.awt.Color(102, 102, 102));
        pnlShortcutNotes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ic_assignment_white_48dp_1x.png"))); // NOI18N
        jLabel12.setToolTipText("Book Download");
        pnlShortcutNotes.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 50, 60));

        pnlShortcutDash.add(pnlShortcutNotes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 70, 60));

        pnlShortcutIssuedBook.setBackground(new java.awt.Color(102, 102, 102));
        pnlShortcutIssuedBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlShortcutIssuedBookMouseClicked(evt);
            }
        });
        pnlShortcutIssuedBook.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ic_collections_bookmark_white_48dp_1x.png"))); // NOI18N
        jLabel13.setToolTipText("Issued Books");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });
        pnlShortcutIssuedBook.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 9, -1, 50));

        pnlShortcutDash.add(pnlShortcutIssuedBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 70, 70));

        pnlShortcutEbookdownload.setBackground(new java.awt.Color(102, 102, 102));
        pnlShortcutEbookdownload.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ic_cloud_download_white_48dp_1x.png"))); // NOI18N
        jLabel16.setToolTipText("Book Download");
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });
        pnlShortcutEbookdownload.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 9, -1, 50));

        pnlShortcutDash.add(pnlShortcutEbookdownload, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 70, 70));

        pnlShortcutJoinGroup.setBackground(new java.awt.Color(102, 102, 102));
        pnlShortcutJoinGroup.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ic_group_add_white_48dp_1x.png"))); // NOI18N
        jLabel19.setToolTipText("Book Download");
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });
        pnlShortcutJoinGroup.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 50, 60));

        pnlShortcutDash.add(pnlShortcutJoinGroup, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 70, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlTask, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlDashView, javax.swing.GroupLayout.PREFERRED_SIZE, 697, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlShortcutDash, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTask, javax.swing.GroupLayout.DEFAULT_SIZE, 581, Short.MAX_VALUE)
            .addComponent(pnlDashView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pnlShortcutDash, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed

    private void txtBranchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBranchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBranchActionPerformed

    private void txtEmailIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailIdActionPerformed

    private void txtMobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMobileActionPerformed

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
new eBookPdf(username).setVisible(true);
this.dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_jLabel16MouseClicked

    private void pnlIssuedBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlIssuedBookMouseClicked
        pnlWork.setVisible(true);
        pnlIssuedBookWork.setVisible(true);
        pnlShortcutDash.setVisible(true);
    }//GEN-LAST:event_pnlIssuedBookMouseClicked

    private void pnlShortcutIssuedBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlShortcutIssuedBookMouseClicked
        pnlWork.setVisible(true);
        pnlIssuedBookWork.setVisible(true);
    }//GEN-LAST:event_pnlShortcutIssuedBookMouseClicked

    private void pnlJoinGroupMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlJoinGroupMouseClicked
        new joinGroup().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_pnlJoinGroupMouseClicked

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
       new joinGroup(username).setVisible(true);
       this.dispose();
    }//GEN-LAST:event_jLabel19MouseClicked

    private void pnlEbookDownloadMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlEbookDownloadMouseClicked
new eBookPdf().setVisible(true);
this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_pnlEbookDownloadMouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
      try{String sql=String.format("select Bid,bookname,bookAuthor where Sid='%s'",username);
      ResultSet rs=DBConnection.executeQuery(sql);
      DBConnection.prepareTable(rs);}catch(Exception e){
          System.out.println("table show");
      }
      
    }//GEN-LAST:event_jLabel13MouseClicked

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        txtName.setEditable(true);
        txtBranch.setEditable(true);
        txtEmailId.setEditable(true);
        txtMobile.setEditable(true);
        btnSave.setVisible(true);
        btnEdit.setVisible(false);
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
       String Name,Branch,EmailId,sql;int Mobile;
       Name=txtName.getText().trim();
       Branch=txtBranch.getText().trim();
       EmailId=txtEmailId.getText().trim();
       Mobile=Integer.parseInt(txtMobile.getText().trim());
       try{sql=String.format("update appuser set name='%s',Designation='%s',email='%s',mobile='%d'where Sid='%s'", Name,Branch,EmailId,Mobile,username);
       DBConnection.executeUpdate(sql);
       DBConnection.commit();btnEdit.setVisible(true);
       btnSave.setVisible(false);}catch(Exception e){System.out.println(e);}
       
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        try{
 String sql=String.format("update appuser set status=1 where Sid='%s'",username);
            System.out.println(""+username);
            DBConnection.executeUpdate(sql);
            DBConnection.commit();new loginFrameUI().setVisible(true);
this.dispose();
        }catch(Exception e)
        {System.out.println(e);}
        // TODO add your handling code here:
    
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(studentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(studentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(studentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(studentDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new studentDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblEnrollment;
    private javax.swing.JPanel pnlDash;
    private javax.swing.JPanel pnlDashView;
    private javax.swing.JPanel pnlEbookDownload;
    private javax.swing.JPanel pnlIssuedBook;
    private javax.swing.JPanel pnlIssuedBookWork;
    private javax.swing.JPanel pnlJoinGroup;
    private javax.swing.JPanel pnlNotes;
    private javax.swing.JPanel pnlShortcutDash;
    private javax.swing.JPanel pnlShortcutEbookdownload;
    private javax.swing.JPanel pnlShortcutIssuedBook;
    private javax.swing.JPanel pnlShortcutJoinGroup;
    private javax.swing.JPanel pnlShortcutNotes;
    private javax.swing.JPanel pnlTask;
    private javax.swing.JPanel pnlWork;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtBranch;
    private javax.swing.JTextField txtEmailId;
    private javax.swing.JTextField txtMobile;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
