
import java.awt.Color;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Locale;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author sourabh
 */
public class teacherDashboard extends javax.swing.JFrame {

    String username;

    /**
     * Creates new form teacherDashboard
     *
     * @param name
     */
    public teacherDashboard(String name) {
        this();
        this.username = name;
        try {
            String sql = String.format("select*from appuser where Sid='%s'", username);
            ResultSet rs = DBConnection.executeQuery(sql);
            if (rs.next()) {
                lblEnrollment.setText(rs.getString("Sid"));
                txtName.setText(rs.getString("name"));
                txtDesc.setText(rs.getString("Designation"));
                txtEmail.setText(rs.getString("emailid"));
            }

        } catch (Exception e) {
            System.out.println("" + e);
        }

    }

    public teacherDashboard() {
        initComponents();

        this.setLocationRelativeTo(null);
        pnlDashView.setBackground(new Color(0, 0, 0, 0));
        pnlSidePane.setBackground(new Color(0, 0, 0, 111));
        pnlTask.setBackground(new Color(0, 0, 0, 111));
        pnlDash.setBackground(new Color(0, 0, 0, 0));
        pnlShortcutDash.setBackground(new Color(0, 0, 0, 111));
        this.setBackground(new Color(0, 0, 0, 100));
        pnlShortcutBook.setBackground(new Color(0, 0, 0, 0));
        pnlShortcutShow.setBackground(new Color(0, 0, 0, 0));
        pnlShortcutEdit.setBackground(new Color(0, 0, 0, 0));
        pnlShortcutIssue.setBackground(new Color(0, 0, 0, 0));
        pnlShortcutReturn.setBackground(new Color(0, 0, 0, 0));
        //  pnlShortcutPdf.setBackground(new Color(0,0,0,0));
        pnlShortcutBook.setBackground(new Color(0, 0, 0, 0));
        pnlShortcutStudents.setBackground(new Color(0, 0, 0, 0));
        btnLogOut.setBorder(null);
        btnLogOut.setBackground(new Color(0, 0, 0, 0));
        pnlShortcutDash.setVisible(false);
        pnlAddBookWork.setVisible(false);
        pnlEditBookWork.setVisible(true);
        //jPanel2.setBackground(new Color(0,0,0,0));
        pnlEditBookWork.setVisible(false);
        pnlIssueBookWork.setVisible(false);
        pnlShowBookWork.setVisible(false);
        pnlReturnBookWork.setVisible(false);
        pnlShowStudentWork.setVisible(false);
        btnSave.setVisible(false);
        System.out.println(jPanel2.getHeight() + "  " + jPanel2.getWidth() + " " + jPanel2.getBounds());
        System.out.println(pnlEditBookWork.getBounds());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlDashView = new javax.swing.JPanel();
        pnlSidePane = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        pnlTask = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAdd = new javax.swing.JTextArea();
        jLabel24 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtDesc = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtMobile = new javax.swing.JTextField();
        btnEditProfile = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnLogOut = new javax.swing.JButton();
        lblEnrollment = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        pnlShowStudentWork = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblStudent = new javax.swing.JTable();
        pnlReturnBookWork = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        btnReturnBook = new javax.swing.JButton();
        pnlShowBookWork = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblShowBook = new javax.swing.JTable();
        pnlIssueBookWork = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtStudentId = new javax.swing.JTextField();
        txtBookId = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        btnIssue = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        txtIssueDate = new javax.swing.JTextField();
        txtReturnDate = new javax.swing.JTextField();
        pnlAddBookWork = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        txtBId = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        txtBookName = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        txtBookAuthor = new javax.swing.JTextField();
        btnAddBook = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        pnlEditBookWork = new javax.swing.JPanel();
        jLabel35 = new javax.swing.JLabel();
        txtEditBookid = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        txtEditBookName = new javax.swing.JTextField();
        txtEditBookAuthor = new javax.swing.JTextField();
        btnEdit = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        pnlDash = new javax.swing.JPanel();
        pnlShowStudent = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        pnlEditBook = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pnlIssueBook = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        pnlShowBook = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        pnlAddBook = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        pnlReturnBook = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        pnlShortcutDash = new javax.swing.JPanel();
        pnlShortcutBook = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        pnlShortcutEdit = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        pnlShortcutIssue = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        pnlShortcutShow = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        pnlShortcutReturn = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        pnlShortcutStudents = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlDashView.setBackground(new java.awt.Color(255, 255, 255));
        pnlDashView.setOpaque(false);
        pnlDashView.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlSidePane.setBackground(new java.awt.Color(51, 51, 51));
        pnlSidePane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ic_account_circle_white_48dp_2x.png"))); // NOI18N
        pnlSidePane.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 100, 120));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Library Id");
        pnlSidePane.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 100, 20));

        pnlTask.setBackground(new java.awt.Color(51, 51, 51));
        pnlTask.setOpaque(false);
        pnlTask.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtAdd.setBackground(new java.awt.Color(51, 51, 51));
        txtAdd.setColumns(20);
        txtAdd.setForeground(new java.awt.Color(255, 255, 255));
        txtAdd.setRows(2);
        jScrollPane2.setViewportView(txtAdd);

        pnlTask.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 210, 70));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("EmailId");
        pnlTask.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 50, 20));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Name");
        pnlTask.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 50, 20));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Designation");
        pnlTask.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 80, 20));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Mobile No");
        pnlTask.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 60, 20));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Address");
        pnlTask.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 70, 20));

        txtName.setEditable(false);
        txtName.setBackground(new java.awt.Color(51, 51, 51));
        txtName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtName.setForeground(new java.awt.Color(255, 255, 255));
        txtName.setBorder(null);
        txtName.setOpaque(false);
        pnlTask.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 210, 20));

        txtDesc.setEditable(false);
        txtDesc.setBackground(new java.awt.Color(51, 51, 51));
        txtDesc.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtDesc.setForeground(new java.awt.Color(255, 255, 255));
        txtDesc.setBorder(null);
        txtDesc.setOpaque(false);
        pnlTask.add(txtDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 200, 20));

        txtEmail.setEditable(false);
        txtEmail.setBackground(new java.awt.Color(51, 51, 51));
        txtEmail.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtEmail.setForeground(new java.awt.Color(255, 255, 255));
        txtEmail.setBorder(null);
        txtEmail.setOpaque(false);
        pnlTask.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 210, 20));

        txtMobile.setEditable(false);
        txtMobile.setBackground(new java.awt.Color(51, 51, 51));
        txtMobile.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtMobile.setForeground(new java.awt.Color(255, 255, 255));
        txtMobile.setBorder(null);
        txtMobile.setOpaque(false);
        txtMobile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMobileActionPerformed(evt);
            }
        });
        pnlTask.add(txtMobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 200, 20));

        btnEditProfile.setBackground(new java.awt.Color(255, 255, 255));
        btnEditProfile.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnEditProfile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ic_mode_edit_black_24dp_1x.png"))); // NOI18N
        btnEditProfile.setText("Edit");
        btnEditProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditProfileActionPerformed(evt);
            }
        });
        pnlTask.add(btnEditProfile, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 440, 100, 23));

        btnSave.setBackground(new java.awt.Color(153, 153, 153));
        btnSave.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        pnlTask.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 440, 100, 23));

        pnlSidePane.add(pnlTask, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 240, 480));

        btnLogOut.setBackground(new java.awt.Color(51, 51, 51));
        btnLogOut.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLogOut.setForeground(new java.awt.Color(255, 255, 255));
        btnLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ic_exit_to_app_white_24dp_1x.png"))); // NOI18N
        btnLogOut.setText("LogOut");
        btnLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogOutMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                btnLogOutMouseReleased(evt);
            }
        });
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });
        pnlSidePane.add(btnLogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 10, 110, 30));

        lblEnrollment.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblEnrollment.setForeground(new java.awt.Color(255, 255, 255));
        pnlSidePane.add(lblEnrollment, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 90, 20));

        pnlDashView.add(pnlSidePane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 240, 620));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("DashBoard");
        pnlDashView.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 670, 50));

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlShowStudentWork.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlShowStudentWorkMouseClicked(evt);
            }
        });
        pnlShowStudentWork.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblStudent.setBackground(new java.awt.Color(102, 102, 102));
        tblStudent.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tblStudent.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tblStudent.setForeground(new java.awt.Color(255, 255, 255));
        tblStudent.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "User Id", "User Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblStudent.setOpaque(false);
        jScrollPane3.setViewportView(tblStudent);
        if (tblStudent.getColumnModel().getColumnCount() > 0) {
            tblStudent.getColumnModel().getColumn(0).setPreferredWidth(10);
        }

        pnlShowStudentWork.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 340));

        jPanel2.add(pnlShowStudentWork, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 600, 340));

        pnlReturnBookWork.setBackground(new java.awt.Color(102, 102, 102));
        pnlReturnBookWork.setForeground(new java.awt.Color(255, 255, 255));
        pnlReturnBookWork.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Book Id");
        pnlReturnBookWork.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, -1));

        jTextField1.setBackground(new java.awt.Color(153, 153, 153));
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setCaretColor(new java.awt.Color(255, 255, 255));
        pnlReturnBookWork.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 140, -1));

        jTextField2.setBackground(new java.awt.Color(153, 153, 153));
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setCaretColor(new java.awt.Color(255, 255, 255));
        pnlReturnBookWork.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, 150, -1));

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("Student Id");
        pnlReturnBookWork.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, -1, -1));

        jSeparator9.setForeground(new java.awt.Color(255, 255, 255));
        pnlReturnBookWork.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 93, 140, -1));

        jSeparator10.setForeground(new java.awt.Color(255, 255, 255));
        pnlReturnBookWork.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 93, 150, -1));

        btnReturnBook.setBackground(new java.awt.Color(51, 51, 51));
        btnReturnBook.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnReturnBook.setForeground(new java.awt.Color(255, 255, 255));
        btnReturnBook.setText("Return Book");
        pnlReturnBookWork.add(btnReturnBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, -1, -1));

        jPanel2.add(pnlReturnBookWork, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 100, 400, 175));

        pnlShowBookWork.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlShowBookWorkMouseClicked(evt);
            }
        });
        pnlShowBookWork.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblShowBook.setAutoCreateRowSorter(true);
        tblShowBook.setBackground(new java.awt.Color(102, 102, 102));
        tblShowBook.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tblShowBook.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tblShowBook.setForeground(new java.awt.Color(255, 255, 255));
        tblShowBook.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Book Id", "Book Name", "Book Author"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblShowBook);

        pnlShowBookWork.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 340));

        jPanel2.add(pnlShowBookWork, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 600, 340));

        pnlIssueBookWork.setBackground(new java.awt.Color(102, 102, 102));
        pnlIssueBookWork.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Student Id");
        pnlIssueBookWork.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 50, 80, 20));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Return Date");
        pnlIssueBookWork.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 80, 20));

        txtStudentId.setBackground(new java.awt.Color(153, 153, 153));
        txtStudentId.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtStudentId.setForeground(new java.awt.Color(255, 255, 255));
        txtStudentId.setCaretColor(new java.awt.Color(255, 255, 255));
        pnlIssueBookWork.add(txtStudentId, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 80, 140, -1));

        txtBookId.setBackground(new java.awt.Color(153, 153, 153));
        txtBookId.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtBookId.setForeground(new java.awt.Color(255, 255, 255));
        txtBookId.setCaretColor(new java.awt.Color(255, 255, 255));
        pnlIssueBookWork.add(txtBookId, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 140, -1));

        jSeparator7.setForeground(new java.awt.Color(255, 255, 255));
        pnlIssueBookWork.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 105, 140, -1));
        pnlIssueBookWork.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 105, 140, -1));

        btnIssue.setBackground(new java.awt.Color(51, 51, 51));
        btnIssue.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnIssue.setForeground(new java.awt.Color(255, 255, 255));
        btnIssue.setText("Issue");
        btnIssue.setBorder(null);
        btnIssue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIssueActionPerformed(evt);
            }
        });
        pnlIssueBookWork.add(btnIssue, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 230, 80, 20));

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(255, 255, 255));
        jLabel37.setText("Book Id");
        pnlIssueBookWork.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 60, 20));

        jLabel40.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("Issue Date");
        pnlIssueBookWork.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 70, 20));

        txtIssueDate.setBackground(new java.awt.Color(153, 153, 153));
        txtIssueDate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtIssueDate.setForeground(new java.awt.Color(255, 255, 255));
        txtIssueDate.setCaretColor(new java.awt.Color(255, 255, 255));
        txtIssueDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIssueDateActionPerformed(evt);
            }
        });
        pnlIssueBookWork.add(txtIssueDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 140, -1));

        txtReturnDate.setBackground(new java.awt.Color(153, 153, 153));
        txtReturnDate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtReturnDate.setForeground(new java.awt.Color(255, 255, 255));
        txtReturnDate.setCaretColor(new java.awt.Color(255, 255, 255));
        pnlIssueBookWork.add(txtReturnDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 140, -1));

        jPanel2.add(pnlIssueBookWork, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 75, 450, 350));

        pnlAddBookWork.setBackground(new java.awt.Color(102, 102, 102));
        pnlAddBookWork.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel32.setBackground(new java.awt.Color(153, 153, 153));
        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Book Id");
        pnlAddBookWork.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        txtBId.setBackground(new java.awt.Color(153, 153, 153));
        txtBId.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtBId.setForeground(new java.awt.Color(255, 255, 255));
        txtBId.setBorder(null);
        txtBId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBIdActionPerformed(evt);
            }
        });
        pnlAddBookWork.add(txtBId, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 100, 20));

        jLabel33.setBackground(new java.awt.Color(153, 153, 153));
        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Book Name");
        pnlAddBookWork.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        txtBookName.setBackground(new java.awt.Color(153, 153, 153));
        txtBookName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtBookName.setForeground(new java.awt.Color(255, 255, 255));
        txtBookName.setBorder(null);
        pnlAddBookWork.add(txtBookName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 190, 20));

        jLabel34.setBackground(new java.awt.Color(153, 153, 153));
        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Book Author");
        pnlAddBookWork.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 80, -1, -1));

        txtBookAuthor.setBackground(new java.awt.Color(153, 153, 153));
        txtBookAuthor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtBookAuthor.setForeground(new java.awt.Color(255, 255, 255));
        txtBookAuthor.setBorder(null);
        txtBookAuthor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBookAuthorActionPerformed(evt);
            }
        });
        pnlAddBookWork.add(txtBookAuthor, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 100, 230, 20));

        btnAddBook.setBackground(new java.awt.Color(51, 51, 51));
        btnAddBook.setForeground(new java.awt.Color(255, 255, 255));
        btnAddBook.setText("Add");
        btnAddBook.setToolTipText("Add Book");
        btnAddBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBookActionPerformed(evt);
            }
        });
        pnlAddBookWork.add(btnAddBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 80, -1));
        pnlAddBookWork.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 190, 20));
        pnlAddBookWork.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 62, 100, 10));
        pnlAddBookWork.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 230, -1));

        jPanel2.add(pnlAddBookWork, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 95, 530, 190));

        pnlEditBookWork.setBackground(new java.awt.Color(102, 102, 102));
        pnlEditBookWork.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Book Author");
        pnlEditBookWork.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, -1, 20));

        txtEditBookid.setBackground(new java.awt.Color(153, 153, 153));
        txtEditBookid.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtEditBookid.setForeground(new java.awt.Color(255, 255, 255));
        txtEditBookid.setBorder(null);
        pnlEditBookWork.add(txtEditBookid, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 70, 20));
        pnlEditBookWork.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 40, 70, 10));

        txtEditBookName.setBackground(new java.awt.Color(153, 153, 153));
        txtEditBookName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtEditBookName.setForeground(new java.awt.Color(255, 255, 255));
        txtEditBookName.setBorder(null);
        txtEditBookName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEditBookNameActionPerformed(evt);
            }
        });
        pnlEditBookWork.add(txtEditBookName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 170, 20));

        txtEditBookAuthor.setBackground(new java.awt.Color(153, 153, 153));
        txtEditBookAuthor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtEditBookAuthor.setForeground(new java.awt.Color(255, 255, 255));
        txtEditBookAuthor.setBorder(null);
        pnlEditBookWork.add(txtEditBookAuthor, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 190, 20));

        btnEdit.setBackground(new java.awt.Color(51, 51, 51));
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        pnlEditBookWork.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 60, -1));
        pnlEditBookWork.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 170, -1));
        pnlEditBookWork.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 190, -1));

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("Book Id");
        pnlEditBookWork.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, 20));

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(255, 255, 255));
        jLabel39.setText("Book Name");
        pnlEditBookWork.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, 20));

        btnSearch.setBackground(new java.awt.Color(102, 102, 102));
        btnSearch.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSearch.setForeground(new java.awt.Color(255, 255, 255));
        btnSearch.setText("search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        pnlEditBookWork.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, -1));

        jPanel2.add(pnlEditBookWork, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 75, 450, 170));

        pnlDash.setBackground(new java.awt.Color(204, 204, 204));
        pnlDash.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlShowStudent.setBackground(new java.awt.Color(102, 102, 102));
        pnlShowStudent.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlShowStudentMouseClicked(evt);
            }
        });
        pnlShowStudent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Show Students");
        pnlShowStudent.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 140, 50));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ic_account_circle_black_48dp_1x.png"))); // NOI18N
        pnlShowStudent.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, -1, 60));

        pnlDash.add(pnlShowStudent, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 190, 80));

        pnlEditBook.setBackground(new java.awt.Color(102, 102, 102));
        pnlEditBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlEditBookMouseClicked(evt);
            }
        });
        pnlEditBook.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ic_edit_black_48dp_1x.png"))); // NOI18N
        pnlEditBook.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Edit Books");
        pnlEditBook.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, 40));

        pnlDash.add(pnlEditBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 190, 80));

        pnlIssueBook.setBackground(new java.awt.Color(102, 102, 102));
        pnlIssueBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlIssueBookMouseClicked(evt);
            }
        });
        pnlIssueBook.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setIcon(new javax.swing.ImageIcon("S:\\ic_book_black_48dp\\web\\ic_book_black_48dp_1x.png")); // NOI18N
        pnlIssueBook.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 60, 60));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Issue books");
        pnlIssueBook.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, -1));

        pnlDash.add(pnlIssueBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, 190, 80));

        pnlShowBook.setBackground(new java.awt.Color(102, 102, 102));
        pnlShowBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlShowBookMouseClicked(evt);
            }
        });
        pnlShowBook.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ic_line_weight_black_48dp_1x.png"))); // NOI18N
        pnlShowBook.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 8, -1, 60));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Show Books");
        pnlShowBook.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, 40));

        pnlDash.add(pnlShowBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 190, 80));

        pnlAddBook.setBackground(new java.awt.Color(102, 102, 102));
        pnlAddBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlAddBookMouseClicked(evt);
            }
        });
        pnlAddBook.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ic_library_books_black_48dp_1x.png"))); // NOI18N
        pnlAddBook.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 60, 80));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Add Books");
        pnlAddBook.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, 100, 40));

        pnlDash.add(pnlAddBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 190, 80));

        pnlReturnBook.setBackground(new java.awt.Color(102, 102, 102));
        pnlReturnBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlReturnBookMouseClicked(evt);
            }
        });
        pnlReturnBook.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ic_keyboard_return_white_48dp_1x.png"))); // NOI18N
        pnlReturnBook.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 50, 40));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ic_library_books_black_48dp_1x.png"))); // NOI18N
        pnlReturnBook.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 50, 60));

        jLabel17.setBackground(new java.awt.Color(102, 102, 102));
        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("Return Books");
        pnlReturnBook.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 140, 40));

        pnlDash.add(pnlReturnBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 190, 80));

        jPanel2.add(pnlDash, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 700, 390));

        pnlDashView.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 720, 500));

        getContentPane().add(pnlDashView, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 970, 640));

        pnlShortcutDash.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlShortcutBook.setBackground(new java.awt.Color(102, 102, 102));
        pnlShortcutBook.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlShortcutBookMouseClicked(evt);
            }
        });
        pnlShortcutBook.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setBackground(new java.awt.Color(102, 102, 102));
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ic_library_books_white_48dp_1x.png"))); // NOI18N
        jLabel19.setToolTipText("Add Books");
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });
        pnlShortcutBook.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 50, 60));

        pnlShortcutDash.add(pnlShortcutBook, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 70, 60));

        pnlShortcutEdit.setBackground(new java.awt.Color(102, 102, 102));
        pnlShortcutEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlShortcutEditMouseClicked(evt);
            }
        });
        pnlShortcutEdit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setBackground(new java.awt.Color(51, 51, 51));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ic_mode_edit_white_48dp_1x.png"))); // NOI18N
        jLabel22.setToolTipText("Edit Books");
        jLabel22.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel22MouseClicked(evt);
            }
        });
        pnlShortcutEdit.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        pnlShortcutDash.add(pnlShortcutEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 70, 60));

        pnlShortcutIssue.setBackground(new java.awt.Color(102, 102, 102));
        pnlShortcutIssue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlShortcutIssueMouseClicked(evt);
            }
        });

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ic_book_white_48dp_1x.png"))); // NOI18N
        jLabel27.setToolTipText("Issue Books");
        jLabel27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel27MouseClicked(evt);
            }
        });
        pnlShortcutIssue.add(jLabel27);

        pnlShortcutDash.add(pnlShortcutIssue, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 70, 60));

        pnlShortcutShow.setBackground(new java.awt.Color(102, 102, 102));
        pnlShortcutShow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlShortcutShowMouseClicked(evt);
            }
        });
        pnlShortcutShow.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ic_line_weight_white_48dp_1x.png"))); // NOI18N
        jLabel28.setToolTipText("Show Books");
        jLabel28.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel28MouseClicked(evt);
            }
        });
        pnlShortcutShow.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 50));

        pnlShortcutDash.add(pnlShortcutShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 70, 50));

        pnlShortcutReturn.setBackground(new java.awt.Color(102, 102, 102));
        pnlShortcutReturn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ic_keyboard_return_white_48dp_1x.png"))); // NOI18N
        jLabel30.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel30MouseClicked(evt);
            }
        });
        pnlShortcutReturn.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 50));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ic_library_books_white_48dp_1x.png"))); // NOI18N
        jLabel29.setToolTipText("ReturnBooks");
        pnlShortcutReturn.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        pnlShortcutDash.add(pnlShortcutReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 70, 60));

        pnlShortcutStudents.setBackground(new java.awt.Color(102, 102, 102));
        pnlShortcutStudents.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnlShortcutStudentsMouseClicked(evt);
            }
        });
        pnlShortcutStudents.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ic_account_circle_white_48dp_1x.png"))); // NOI18N
        jLabel31.setToolTipText("Show Student");
        jLabel31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel31MouseClicked(evt);
            }
        });
        pnlShortcutStudents.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -2, -1, 60));

        pnlShortcutDash.add(pnlShortcutStudents, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 70, 60));

        getContentPane().add(pnlShortcutDash, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 0, 70, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        try {
            String sql = String.format("update appuser set status=1 where Sid='%s'", username);
            DBConnection.executeUpdate(sql);
            DBConnection.commit();
        } catch (Exception e) {
            System.out.println(e);
        }
        new loginFrameUI().setVisible(true);
        this.dispose();// TODO add your handling code here:
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void txtMobileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMobileActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMobileActionPerformed

    private void btnEditProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditProfileActionPerformed
        txtName.setEditable(true);
        txtDesc.setEditable(true);
        txtEmail.setEditable(true);
        txtMobile.setEditable(true);
        btnEdit.setVisible(false);
        btnSave.setVisible(true);

    }//GEN-LAST:event_btnEditProfileActionPerformed

    private void pnlAddBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlAddBookMouseClicked
        pnlDash.setVisible(false);
        pnlShortcutDash.setVisible(true);
        pnlAddBookWork.setVisible(true);

    }//GEN-LAST:event_pnlAddBookMouseClicked

    private void pnlEditBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlEditBookMouseClicked
        pnlDash.setVisible(false);
        pnlShortcutDash.setVisible(true);
        pnlEditBookWork.setVisible(true);


    }//GEN-LAST:event_pnlEditBookMouseClicked

    private void pnlIssueBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlIssueBookMouseClicked
        pnlDash.setVisible(false);
        pnlShortcutDash.setVisible(true);
        pnlIssueBookWork.setVisible(true);

    }//GEN-LAST:event_pnlIssueBookMouseClicked

    private void pnlShowBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlShowBookMouseClicked
        pnlDash.setVisible(false);
        pnlShortcutDash.setVisible(true);
        pnlShowBookWork.setVisible(true);
        pnlAddBookWork.setVisible(false);
        pnlEditBookWork.setVisible(false);
        pnlIssueBookWork.setVisible(false);
    }//GEN-LAST:event_pnlShowBookMouseClicked

    private void pnlReturnBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlReturnBookMouseClicked
        pnlDash.setVisible(false);
        pnlShortcutDash.setVisible(true);
        pnlReturnBookWork.setVisible(true);
    }//GEN-LAST:event_pnlReturnBookMouseClicked

    private void pnlShowStudentMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlShowStudentMouseClicked
        pnlDash.setVisible(false);
        pnlShortcutDash.setVisible(true);
        pnlShowStudentWork.setVisible(true);
    }//GEN-LAST:event_pnlShowStudentMouseClicked

    private void btnLogOutMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogOutMouseReleased
        btnLogOut.setBackground(new Color(0, 0, 0, 0));
    }//GEN-LAST:event_btnLogOutMouseReleased

    private void txtBookAuthorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBookAuthorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBookAuthorActionPerformed

    private void pnlShortcutBookMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlShortcutBookMouseClicked

        pnlDash.setVisible(false);
        pnlEditBookWork.setVisible(false);
        pnlIssueBookWork.setVisible(false);
        pnlAddBookWork.setVisible(true);
        pnlShowBookWork.setVisible(false);
        pnlReturnBookWork.setVisible(false);

    }//GEN-LAST:event_pnlShortcutBookMouseClicked

    private void txtEditBookNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEditBookNameActionPerformed

    }//GEN-LAST:event_txtEditBookNameActionPerformed

    private void pnlShortcutEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlShortcutEditMouseClicked
        pnlAddBookWork.setVisible(false);
        pnlDash.setVisible(false);
        pnlIssueBookWork.setVisible(false);
        pnlEditBookWork.setVisible(true);
        pnlShowBookWork.setVisible(false);
        pnlReturnBookWork.setVisible(false);
        pnlShowStudentWork.setVisible(false);
    }//GEN-LAST:event_pnlShortcutEditMouseClicked

    private void btnIssueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIssueActionPerformed
        String Bid, Sid;
        String IssueDate, ReturnDate;
        Bid = txtBookId.getText();
        Sid = txtStudentId.getText();
        IssueDate = txtIssueDate.getText();
        ReturnDate = txtReturnDate.getText();
        try {
            String sql = String.format("insert into issue values('%s','%s','%s,'%s')", Bid, Sid, IssueDate, ReturnDate);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Date is Irrelevent \n student id/book id may not correct");
        }

    }//GEN-LAST:event_btnIssueActionPerformed

    private void jLabel22MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel22MouseClicked
        pnlAddBookWork.setVisible(false);
        pnlDash.setVisible(false);
        pnlEditBookWork.setVisible(true);
        pnlIssueBookWork.setVisible(false);
        pnlShowBookWork.setVisible(false);
        pnlReturnBookWork.setVisible(false);
        pnlShowStudentWork.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel22MouseClicked

    private void pnlShortcutIssueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlShortcutIssueMouseClicked
        pnlAddBookWork.setVisible(false);
        pnlDash.setVisible(false);
        pnlEditBookWork.setVisible(false);
        pnlIssueBookWork.setVisible(true);
        pnlShowBookWork.setVisible(false);
        pnlReturnBookWork.setVisible(false);
        pnlShowStudentWork.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_pnlShortcutIssueMouseClicked

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked

        pnlDash.setVisible(false);
        pnlEditBookWork.setVisible(false);
        pnlIssueBookWork.setVisible(false);
        pnlAddBookWork.setVisible(true);
        pnlShowBookWork.setVisible(false);
        pnlReturnBookWork.setVisible(false);
        pnlShowStudentWork.setVisible(false);
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jLabel27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel27MouseClicked
        pnlDash.setVisible(false);
        pnlEditBookWork.setVisible(false);
        pnlIssueBookWork.setVisible(true);
        pnlAddBookWork.setVisible(false);
        pnlShowBookWork.setVisible(false);
        pnlReturnBookWork.setVisible(false);
        pnlShowStudentWork.setVisible(false);
    }//GEN-LAST:event_jLabel27MouseClicked

    private void jLabel28MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel28MouseClicked
        pnlShowBookWork.setVisible(true);
        pnlDash.setVisible(false);
        pnlEditBookWork.setVisible(false);
        pnlIssueBookWork.setVisible(false);
        pnlAddBookWork.setVisible(false);
        pnlReturnBookWork.setVisible(false);
        pnlShowStudentWork.setVisible(false);
        pnlShowBookWork.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel28MouseClicked

    private void jLabel30MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel30MouseClicked
        pnlDash.setVisible(false);
        pnlEditBookWork.setVisible(false);
        pnlIssueBookWork.setVisible(false);
        pnlAddBookWork.setVisible(false);
        pnlShowBookWork.setVisible(false);
        pnlReturnBookWork.setVisible(true);
        pnlShowStudentWork.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_jLabel30MouseClicked

    private void jLabel31MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel31MouseClicked
        pnlDash.setVisible(false);
        pnlEditBookWork.setVisible(false);
        pnlIssueBookWork.setVisible(false);
        pnlAddBookWork.setVisible(false);
        pnlShowBookWork.setVisible(false);
        pnlReturnBookWork.setVisible(false);
        pnlShowStudentWork.setVisible(true);
    }//GEN-LAST:event_jLabel31MouseClicked

    private void btnAddBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBookActionPerformed
        String Bid, BookName, BookAuthor;
        int status = 1;
        Bid = txtBId.getText();
        BookName = txtBookName.getText();
        BookAuthor = txtBookAuthor.getText();
        try {
            String sql = String.format("insert into book values('%s','%s','%s','%d')", Bid, BookName, BookAuthor, status);
            DBConnection.executeUpdate(sql);
            DBConnection.commit();

        } catch (Exception e) {
            System.out.println(e.getMessage());
            JOptionPane.showMessageDialog(null, "Book cannot be added");
        }


    }//GEN-LAST:event_btnAddBookActionPerformed

    private void txtBIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBIdActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        String EditBookid, EditBookName, EditBookAuthor;
        EditBookid = txtEditBookid.getText();
        EditBookName = txtEditBookName.getText();
        EditBookAuthor = txtEditBookAuthor.getText();
        try {
            String sql = String.format("update book set bookname='%s' ,bookAuthor='%s' where Bid='%s'",  EditBookName, EditBookAuthor,EditBookid);
            DBConnection.executeUpdate(sql);
            DBConnection.commit();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "book cannot be added");
        }

    }//GEN-LAST:event_btnEditActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String EditBookid;
        EditBookid = txtEditBookid.getText();
        try {
            String sql = String.format("Select bookname,bookAuthor from book where Bid='%s'", EditBookid);
            ResultSet rs = DBConnection.executeQuery(sql);
            if (rs.next()) {
                String setBookName = rs.getString("bookname");
                String setBookAuthor = rs.getString("bookauthor");
                txtEditBookName.setText(setBookName);
                txtEditBookAuthor.setText(setBookAuthor);

            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "books not found");
        }

    }//GEN-LAST:event_btnSearchActionPerformed

    private void txtIssueDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIssueDateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIssueDateActionPerformed

    private void btnLogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogOutMouseClicked
        try {
            String sql = String.format("Update appuser set status=1 where Sid='%s'", username);
            DBConnection.executeUpdate(sql);
            DBConnection.commit();
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnLogOutMouseClicked

    private void pnlShowStudentWorkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlShowStudentWorkMouseClicked
        try {
            String sql = String.format("Select Sid ,name from appuser where type='Student'");
            ResultSet rs = DBConnection.executeQuery(sql);
            tblStudent.setModel(DBConnection.prepareTable(rs));
        } catch (Exception e) {
            System.out.println("table");
        }

    }//GEN-LAST:event_pnlShowStudentWorkMouseClicked

    private void pnlShortcutStudentsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlShortcutStudentsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pnlShortcutStudentsMouseClicked

    private void pnlShowBookWorkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlShowBookWorkMouseClicked
        try {
            String sql = String.format("Select Bid,bookname,bookAuthor from book");
            ResultSet rs = DBConnection.executeQuery(sql);
            tblShowBook.setModel(DBConnection.prepareTable(rs));
        } catch (Exception e) {
            System.out.println("table book");
        }  // TODO add your handling code here:
    }//GEN-LAST:event_pnlShowBookWorkMouseClicked

    private void pnlShortcutShowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlShortcutShowMouseClicked

    }//GEN-LAST:event_pnlShortcutShowMouseClicked

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String name, desc, email, sql;
        int mobile;
        name = txtName.getText();
        desc = txtDesc.getText();
        email = txtEmail.getText();
        mobile = Integer.parseInt(txtMobile.getText());
        try {
            sql = String.format("update appuser set name='%s',branch='%s',email='%s',mobile='%d'where Sid='%s'", name, desc, email, mobile, username);
            DBConnection.executeUpdate(sql);
            DBConnection.commit();
            btnSave.setVisible(false);
            btnEdit.setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "profile not edited");
        }

    }//GEN-LAST:event_btnSaveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(teacherDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(teacherDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(teacherDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(teacherDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new teacherDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddBook;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnEditProfile;
    private javax.swing.JButton btnIssue;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnReturnBook;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lblEnrollment;
    private javax.swing.JPanel pnlAddBook;
    private javax.swing.JPanel pnlAddBookWork;
    private javax.swing.JPanel pnlDash;
    private javax.swing.JPanel pnlDashView;
    private javax.swing.JPanel pnlEditBook;
    private javax.swing.JPanel pnlEditBookWork;
    private javax.swing.JPanel pnlIssueBook;
    private javax.swing.JPanel pnlIssueBookWork;
    private javax.swing.JPanel pnlReturnBook;
    private javax.swing.JPanel pnlReturnBookWork;
    private javax.swing.JPanel pnlShortcutBook;
    private javax.swing.JPanel pnlShortcutDash;
    private javax.swing.JPanel pnlShortcutEdit;
    private javax.swing.JPanel pnlShortcutIssue;
    private javax.swing.JPanel pnlShortcutReturn;
    private javax.swing.JPanel pnlShortcutShow;
    private javax.swing.JPanel pnlShortcutStudents;
    private javax.swing.JPanel pnlShowBook;
    private javax.swing.JPanel pnlShowBookWork;
    private javax.swing.JPanel pnlShowStudent;
    private javax.swing.JPanel pnlShowStudentWork;
    private javax.swing.JPanel pnlSidePane;
    private javax.swing.JPanel pnlTask;
    private javax.swing.JTable tblShowBook;
    private javax.swing.JTable tblStudent;
    private javax.swing.JTextArea txtAdd;
    private javax.swing.JTextField txtBId;
    private javax.swing.JTextField txtBookAuthor;
    private javax.swing.JTextField txtBookId;
    private javax.swing.JTextField txtBookName;
    private javax.swing.JTextField txtDesc;
    private javax.swing.JTextField txtEditBookAuthor;
    private javax.swing.JTextField txtEditBookName;
    private javax.swing.JTextField txtEditBookid;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtIssueDate;
    private javax.swing.JTextField txtMobile;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtReturnDate;
    private javax.swing.JTextField txtStudentId;
    // End of variables declaration//GEN-END:variables
}
